Bio 2359 yaml config parser
arteria-project/arteria-delivery pull request #49
Opened 2023-10-10 13:35 UTC by monikaBrandt

**What problems does this PR solve?**
Added a function that can open, read and parse a yaml.config file for organising files prior to delivery. Can be applied on an anlysed project or a single runfolder. The code will resolve regular expressions, using the pattern given in the configuration file, to find source files to link to a destination file. Based on the input and the resolved regular expressions string substitution will be performed to update/resolve paths given in the configuration file.  

**How has the changes been tested?**
Only unittests.

**Reasons for careful code review**
If any of the boxes below are checked, extra careful code review should be inititated.

  - [ ] This PR contains code that could remove data

2023-10-12 11:07 UTC, Aratz reviewed
Great work! My main concern is with the deadlock issue, I think we should merge the glob functionalities first before you can rework this part.

2023-10-12 11:07 UTC, Aratz commented on tests/unit_tests/services/test_organise_service.py
> +        "filter": "(?P<projectid>[\w-]+)/200624_A00834_0183_BHMTFYDRXX_(?P=projectid)_multiqc_report[\w.-]+"})]
```suggestion
        expected_output = [
            (
                "/proj/ngi2016001/incoming/200624_A00834_0183_BHMTFYDRXX/seqreports/project/AB-1234/200624_A00834_0183_BHMTFYDRXX_AB-1234_multiqc_report.html",
                "/proj/ngi2016001/incoming/200624_A00834_0183_BHMTFYDRXX/Projects/AB-1234/200624_A00834_0183_BHMTFYDRXX/200624_A00834_0183_BHMTFYDRXX_AB-1234_multiqc_report.html", 
                {
                    "required": True,
                    "link_type": "softlink",
                    "filter": "(?P<projectid>[\w-]+)/200624_A00834_0183_BHMTFYDRXX_(?P=projectid)_multiqc_report[\w.-]+"
                }
            )
        ]
```

2023-10-12 11:07 UTC, Aratz commented on tests/unit_tests/services/test_organise_service.py
> +        "filter": "(?P<projectid>[\w-]+)/Sample_(?P<samplename>[\w-]+)/(?P=samplename)_S(?P<samplenumber>\d+)_L(?P<lanes>\d+)_R(?P<read>\d)_001.fastq.gz"})]
```suggestion
        expected_output = [
            (
                "/proj/ngi2016001/incoming/200624_A00834_0183_BHMTFYDRXX/Unaligned/AB-1234/Sample_AB-1234-14092/AB-1234-14092_S35_L001_R1_001.fastq.gz",
                "/proj/ngi2016001/incoming/200624_A00834_0183_BHMTFYDRXX/Projects/AB-1234/200624_A00834_0183_BHMTFYDRXX/Sample_AB-1234-14092/AB-1234-14092_S35_L001_R1_001.fastq.gz", 
                {
                    "required": True,
                    "link_type": "softlink",
                    "filter": "(?P<projectid>[\w-]+)/Sample_(?P<samplename>[\w-]+)/(?P=samplename)_S(?P<samplenumber>\d+)_L(?P<lanes>\d+)_R(?P<read>\d)_001.fastq.gz"
                }
            )
        ]
```

2023-10-12 12:53 UTC, monikaBrandt commented on delivery/services/organise_service.py
> +                config_as_list.append((element["source"],element["destination"],element["options"]))
Yes, this part is a bit tricky and I guess we can solve it in a different way. In this case (i.e. this code will be applied on a runfolder not an organized project) this glob will be resolved when the list of possible source files is created. When a glob is trailing a source path everything under that path should be selected and then filtered with a regexp to get the correct runfolder and project. In the other case, the one you are linking to, the identifier projectid is already specified in the source path and there is only one destination. Therefore the glob can be resolved in the copy/linking operation performed by @b97pla code. But maybe I'm building my code on too many assumptions (or too much knowledge) about the data we are linking.

2023-10-12 13:03 UTC, monikaBrandt commented on delivery/services/organise_service.py
> +    def parse_yaml_config(config_file_path, input_key, input_value):
Do you mean that the default value in the config should be input_key: "runfolder" and during parsing this should be substituted to input_key: <runfolder name> and then we use the key input_key to resolve the paths in the config?

2023-10-12 14:13 UTC, monikaBrandt commented on delivery/services/organise_service.py
> +    def parse_yaml_config(config_file_path, input_key, input_value):
Thank you for good comments and feedback! I was wondering more about where we should set the value of runfolder. Let's say we still have the parameter named input_value and input_key is specified in the config as you show above. Will we then just do
config["input_key"] = input_value and then use {input_key} to do substitutions in the rest of the config? we can absolutely have a look at it tomorrow!

2023-10-12 14:48 UTC, Aratz commented on delivery/services/organise_service.py
> +                config_as_list.append((element["source"],element["destination"],element["options"]))
I mean I think this function should work for all possible config files, so you should assume that the source path may sometimes resolve to several files, even when filter is not specified. Maybe we can also sort this out irl.

2023-10-13 10:14 UTC, b97pla requested changes
Great work! :+1:  

like we discussed, I think the code needs some fixes and I hope we clarified a bit how the different parts of the code should interconnect. I will do some fixing up of my PR

2023-10-13 10:14 UTC, b97pla commented on delivery/services/organise_service.py
> +                    destination = ''.join([destination_file, source_file["source_file"].split("/")[-1]])
I don't think this is what we want in the end but we may need to look into that more closely when we look at real examples.

Also, I'd recommend:
```suggestion
                    destination = os.path.join(destination_file, os.path.basename(source_file["source_file"]))
```

2023-10-27 10:51 UTC, b97pla approved these changes
:+1: great work, I think the code is much more readable now!

I had a few comments, mostly just suggestions for further simplification of the code, nothing that affects the functionality (although there were a couple of snags that needs to be fixed).

If you want, I can merge your PR with my code and fix those things directly, or you can update the PR to your preference.

2023-10-27 10:51 UTC, b97pla commented on delivery/services/organise_service.py
> +         Each element consist of a tuple with 3 values
afaict, each element will be a list and not a tuple (which is perfectly fine)

2023-10-27 10:51 UTC, b97pla commented on delivery/services/organise_service.py
> +            config_as_list = config_as_list + OrganiseService.process_file_to_organise(
the `+` operator will add all elements from the second list to the first. use `config_as_list.append()` instead

2023-10-27 10:51 UTC, b97pla commented on delivery/services/organise_service.py
> +        Each element is a tuple
... a list

2023-10-27 10:51 UTC, b97pla commented on delivery/services/organise_service.py
> +
just a suggestion but you could simplify the code below a bit:

```
source_file_dict = {"source_file": file}
if search_re:
  source_file_dict.update(search_re.groupdict())
source_file_list.append(source_file_dict)
```

2023-10-27 10:51 UTC, b97pla commented on delivery/services/organise_service.py
> +            file_to_organise_list.append(
the way "my" function works, it expects the destination to be a full path, i.e. including filename (if it is a file). In other words, you would need to append `os.path.basename(source_file)` to `destination_file`. Another option is that my function takes care of that, which would be closer to how e.g. `cp` and `ln` works on linux, but I assumed my function would be as dumb as possible.. we can have a quick discussion about this.

2023-10-30 08:15 UTC, b97pla commented
👍 Excellent work @monikaBrandt! I will close this and pull the code into a new PR.

2023-10-30 08:15 UTC, closed without merging